### ISSUE TITLE
Deprecate metallb in favor of kube-vip

### ISSUE THREAD

**Issue by onedr0p** [k8s-at-home/template-cluster-k3s#226]
# Details

**Describe the solution you'd like:**

kibe-vip is already installed and used for the control plane, why not extend it to do k8s services as well and remove metallb

**Comment by ndbrew** [comment]
I just went from using kube-vip to metallb for the following reasons:
- Couldn't figure out how to share IP addresses for multiple services
- kube-vip doesn't appear to support the `externaltrafficpolicy` annotation in cases where you want a service to see that actual client IP address instead of the LB IP.

In both cases metallb seemed to have better support and docs for those use-cases.

**Comment by onedr0p** [comment]
After making the PR I linked to this issue I discovered kube-vip doesn't support `externaltrafficpolicy`, safe to say I won't be switching off metallb here until those problems are addressed.

**Comment by onedr0p** [comment]
Going to close this issue, it can be revisited once the above problems have been resolved.

**Comment by rmoreas** [comment]
kube-vib now supports `externalTrafficPolicy` since version 0.5.0: https://kube-vip.io/docs/usage/kubernetes-services/#external-traffic-policy-kube-vip-v050
