### ISSUE TITLE
Traefik 2

### ISSUE THREAD

**Issue by lucawen** [k8s-at-home/template-cluster-k3s#57]
# Details
Change the proxy server from nginx with cert-manager to use Traefik 2

**Comment by onedr0p** [comment]
While I use Traefik in my cluster, ingress-nginx is much easier to configure. This repository is more an example of getting a basic cluster up and running with Flux and SOPS, while the other components can be swapped in or out as needed. If people need help configuring traefik instead of ingress-nginx they are free to open an discussion or chat in our Discord.
